### ISSUE TITLE
order phases don't expire

### ISSUE THREAD

**Issue by BluemlJ** [d120/pyBuchaktion#47]
The last order phase ( may 11th to 21th ) is not expired. Students can order books for this time period. The new phase started with may 22th, is not active yet. 

To reproduce this bug, you can start an attempt to order any book in our system. (tested may 23th)

**Comment by Xiphoseer** [comment]
The title of this issue does not quite reflect the problem. The actual behavior is, that the earliest timeframe that is set to be active on the day the latest version of pyBuchaktion was deployed is the currently active timeframe. If there is no such timeframe, none will be active. This is actually what caused the older bugs #43 and #44 too.

To describe the precise issue: We have a function in the `OrderTimeframeManager` which is available as `OrderTimeframe.objects` that had (until just before writing this) the header `def current(self, date = datetime.now())`. This caused the default value to be evaluated at compile time, which is something that would change all the time in local testing, but would remain constant only in production. Even within the django shell on the server, this would be newly evaluated upon startup of the shell. So when this bug appeared, this function kept behaving as if today was the 18.05. Incidentally, the last release of pyBuchaktion is from nearly the same date.

It is possible that a server restart would have fixed this too, if the behavior is to evaluate the default parameter at class load and not at compile time. The resulting behavior matches the observed in both cases. Anyhow, no further testing needs to be done there, as i've moved the call out of the default argument.
