### ISSUE TITLE
404 Errors on every page appearing randomly

### ISSUE THREAD

**Issue by fdamken** [d120/pyBuchaktion#48]
**Update:** From time to time a random 404 error page is sent by the server. This happens on every page.

**Comment by fdamken** [comment]
Because of the latter, logout is not possible.

**Comment by Xiphoseer** [comment]
Seems to be a very weird caching issue... Reloading the page two times causes the page to load correctly. Any additional testing would be appreciated.

**Comment by BluemlJ** [comment]
Hotfix: delete the hook to pyBuchaktion and set a new one.

**Comment by Xiphoseer** [comment]
My current theory is that some part of django does url caching in some way, and that broke down when it could not write the database to disk. I'm not sure why the rest of the CMS was unaffected, but I'm fairly certain it is not something we do wrong in pyBuchaktion. The only thing I can think of is the `NeverCacheMixin`, but that should have the opposite effect and is both included and missing on pages that exhibited this behavior. Will close the issue for now, to be reopened when it occurs again.
