### ISSUE TITLE
Add image where to find the library number

### ISSUE THREAD

**Issue by fdamken** [d120/pyBuchaktion#50]
In the registration dialog it would be helpful to include an image where to find the library number (and to make clear that it is not the Athene-cardnumber).

**Comment by Xiphoseer** [comment]
Sure, I'll look into that

**Comment by Xiphoseer** [comment]
I've added the ability to include a text describing where to find it as the `library_id_help` key for `DisplayMessage`s. I'd propose to set it to
> Die Büchereinummer die dir von der ULB zugewiesen wurde. Diese muss angegeben werden, wenn du das Buch für dich vorgemerkt haben willst. Du findest sie auf der Rückseite der Athene-Karte unter dem ULB Logo. Normalerweise beginnt sie mit 0017.

> The library id number assigned by the ULB, required for if you want the book to be reserved for you. It is located on the back of your Athene-Card beneath the ULB logo and usually starts with 0017.

respectively. Would that be sufficient or is an image required?

**Comment by akwick** [comment]
A description is sufficient - at least for me - even if a picture is more user friendly.
At least on my Athene-Card, my number is beneath a bar code and not the ULB logo. Perhaps we simply remove the beneath part? 

> Die Büchereinummer die dir von der ULB zugewiesen wurde. Diese muss angegeben werden, wenn du das Buch für dich vorgemerkt haben willst. Du findest sie auf der Rückseite der Athene-Karte. Normalerweise beginnt sie mit 0017.

> The library id number assigned by the ULB, required for if you want the book to be reserved for you. It is located on the back of your Athene-Card  and usually starts with 0017.

Instead, we could add the information that the number consists of [12 digits.](https://www.ulb.tu-darmstadt.de/service/medien/ausleihe/artikel_details_8777.de.jsp)

**Comment by Xiphoseer** [comment]
Ok then. The text can be customized without needing a new deployment. I'll include the 12 digit info as well as the placement beneath both barcode and ULB logo. I initially chose to reference the latter as it has more obvious relation to the ULB and actually has a meaning.
