### ISSUE TITLE
Improve the error message book not found

### ISSUE THREAD

**Issue by akwick** [d120/pyBuchaktion#51]
Search for a valid and an invalid book yields to the following message:

> Entschuldige, keine passenden
> Bücher wurden gefunden!
> Das gesuchte Buch wurde bereits vorgeschlagen, abgelehnt oder als
> veraltetgekennzeichnet. Damit kann dieses Buch nicht bestellt werden

The second sentence should only appear if it is true else it should not appear. 

More details are available in an E-Mail conversation with a student e.g. today 15.8.2017 11:55 for members of Buchaktion@.

**Comment by Xiphoseer** [comment]
Fixed as of 96580da5c3b5847b8ffae3248716e4a0394a28cb. This was an incorrect translation on my part, and was missing the book proposal feature. It now says
> Das gesuchte Buch wurde möglicherweise bereits vorgeschlagen, abgelehnt oder als veraltet gekennzeichnet. Prüfe die komplette Liste um zu sehen ob das zutrifft, ansonsten kannst du uns das Buch vorschlagen.

The problem with showing that sentence conditionally is that this would require another query altogether than what this view currently does. If anyone has a good & complete proposal on how to do book search (as a flowchart) I'll implement that.
