### ISSUE TITLE
SMTPRecipientsRefused

### ISSUE THREAD

**Issue by exploide** [d120/pyBuchaktion#52]
```
Internal Server Error: /en/admin/pyBuchaktion/order/

SMTPRecipientsRefused at /en/admin/pyBuchaktion/order/
{'=?utf-8?q?None?=': (550, b'5.1.1 <=?utf-8?q?None?=>: Recipient address rejected: User unknown in virtual mailbox table')}
```

I propose catching this error and displaying a message, providing information about which email addresses failed.

**Comment by fdamken** [comment]
Would be good instead of just showing "Server Error 500" when ordering books ;)

Am 20. Oktober 2017 11:07:00 MESZ schrieb Jannik Vieten <notifications@github.com>:

**Comment by Xiphoseer** [comment]
Should already be fixed
