### ISSUE TITLE
Hide extraneous order timeframes in the orders-view

### ISSUE THREAD

**Issue by fdamken** [d120/pyBuchaktion#63]

**Comment by Xiphoseer** [comment]
Could you specify that further? Does 'extraneous' refer to timeframes in the past? Is the option to filter by timeframe not sufficent?

**Comment by fdamken** [comment]
Yes, that refers to the timeframes in the past. The filter is nice already, but having over 15 timeframes, searching for the correct one is quite messy. I would like to have a filter for the filter.

Am 21. Juni 2018 09:04:16 MESZ schrieb Xiphoseer <notifications@github.com>:
